version: '3'
services:
  eventrid-backend:
    build:
      context: .
    command: sh -c "while sleep 1000; do :; done"
    ports:
      - 3000:3000
    volumes:
      - ./:/eventrid-backend
      - node_modules:/usr/src/app/node_modules/
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.0.30"
    ports:
      - "8775:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    container_name: eventrid-backend-mysql

  init:
    build: 
      context: .
    command: sh -c "npm ci && npm run seed && npm start"
    volumes:
      - ./:/eventrid-backend
      - node_modules:/usr/src/app/node_modules/
    depends_on:
      - mysql
    ports:
      - 3000:3000

volumes:
  node_modules:
  mysql_data: